# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BluetoothScanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Charts'


  # Pods for BluetoothScanner

  target 'BluetoothScannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BluetoothScannerUITests' do
    # Pods for testing
  end

end
